language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"

# get ready to go
install: "pip install -r requirements.txt"

# run the "tests"
script: nosetests

# for now the default notifications are fine
